version: '3.7'
services:
  go:
    profiles: ["go"]
    image: golang:1.20.0
    working_dir: /app/exercises
    volumes:
      - ./exercises:/app/exercises
      - ./attendance_id:/app/sync/attendance_id
  sync:
    image: ghcr.io/skiller-whale/learnersync:0.2.1
    environment:
      SERVER_URL: https://train.skillerwhale.com/
      WATCHER_BASE_PATH: /app/exercises
      ATTENDANCE_ID_FILE: /app/sync/attendance_id
      WATCHED_EXTS: .go .mod
      IGNORE_DIRS: .git bin
    volumes:
      - ./exercises:/app/exercises
      - ./attendance_id:/app/sync/attendance_id
